<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

# 1 Lists, Arrays & Dictionaries

## 1.1 Let’s compare

## 1.2 Accessing data from a list (or array)

## 1.3 Accessing data from a dictionary

## 1.4 Higher dimensional lists

# 2 Lists vs. Arrays

## 2.1 Size

In [4]:
import numpy as np
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)  
len(py_list_2d)
len(np_array_2d)
np_array_2d.shape

(10, 2)

## 2.2 Arrays are fussy about type

In [7]:
py_list = [1, 1.5, 'A']
np_array = np.array(py_list)
py_list

np_array #np arrays only accept a single type

array(['1', '1.5', 'A'], dtype='<U32')

## 2.3 Adding a number

In [9]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) 
np_array + 10
py_list + 10

TypeError: can only concatenate list (not "int") to list

In [11]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

py_list_1 + py_list_2
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

In [13]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
np_array*2

array([ 2,  4,  6,  8, 10])

## 2.6 Squaring

## 2.7 Asking questions

In [18]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)  

np_array > 3

array([False, False, False,  True,  True])

## 2.8 Mathematics

In [20]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) 

sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function
print(np_array.sum())
print(np_array.max())
print(np_array.min())
print(np_array.mean())
print(np_array.std())


15
5
1
3.0
1.4142135623730951


## Footnotes